### ISSUE TITLE
Unexpected usage at EditorSimpleWorker

### ISSUE THREAD

**Issue by adamjimenez** [bazingaedward/monaco-editor-vue3#23]
I get this error in the console. It still works however..

`
Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (webpack-internal:///./node_modules/monaco-editor-vue3/node_modules/monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js:480:31)
    at eval (webpack-internal:///./node_modules/monaco-editor-vue3/node_modules/monaco-editor/esm/vs/editor/browser/services/webWorker.js:44:30)
Error: Unexpected usage
`

**Comment by Zetaphor** [comment]
This error implies you're trying to use a language type that you haven't loaded the service worker for.

For example if I try and use JS, but I haven't loaded the JS/TS worker:
```js
import jsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker';
import tsWorker from 'monaco-editor/esm/vs/language/typescript/ts.worker?worker';
```
I would get the same error

**Comment by bazingaedward** [comment]
try this or with chatgpt:
```
// main.ts
import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
import tsWorker     from 'monaco-editor/esm/vs/language/typescript/ts.worker?worker';

// 必须在浏览器端执行
self.MonacoEnvironment = {
  getWorker(_, label) {
    if (label === 'typescript' || label === 'javascript') return new tsWorker();
    return new editorWorker();
  }
};

```
